### ISSUE TITLE
Suggestion: Crafttweaker support (or more flexible smelting/casting)

### ISSUE THREAD

**Issue by Ash70** [kitsushadow/forgecraft#24] opened 2017-09-22 13:58 UTC
Would it be possible to have CraftTweaker support for the crucibles? It would probably mean changing the way they work on code-level (? I think).
If it would be possible to store:
   - temperature (needed in the bloomery)
   - time (both heating and cooling) and 
   - output-item
as NBT data, we could create our own crucible/smelting materials.

This would also mean that all tool-heads would also need to have NBT-data containing their material (not using the anvil recipes, but using the casting molds). 

Basically that would make the whole process crafttweaker compatible, because then we can make a crafting table recipe with a crucible as output, and we could make any tool (added by other mods) by using the tool head in a crafting table recipe.

e.g.
```
var output = <forgecraft:filled_crucible>.withTag({Temperature: 2000, Time: 1200, Output: "minecraft:gold_ingot"});

recipes.addShapeless(output, [<forgecraft:empty_crucible>], [ingredient1], [ingredient2], etc.);

recipes.addShaped(<minecraft:golden_pickaxe>, [
[null, <forgecraft:pickaxe_head>.onlyWithTag({Material: "gold"}), null],
[null, <ore:cordagegeneral>, null],
[null, <minecraft:stick>, null]);
```
By putting all the data in NBT the whole proces become more flexible. The idea needs some tweaking, I just put this together from the top of my head. 
But I would understand if it is too much work or undo-able for you. :-) I'm liking this mod either way.

**Comment by kitsushadow** [comment] 2017-09-22 16:22
Thanks for the really detailed feedback. The issue is how to transition the
crucible via the tongs. Tool heads store everything in NBT and the tongs
store and transfer nbt data but the tongs nbt data stores the type of item
or block its holding. Which makes it really difficult.

I do believe craft tweaker support to some extent is definitely necessary

**Comment by Ash70** [comment] 2017-09-23 11:03
I see. I made a lot of assumptions since I am not entirely sure how the casting mechanism works. I made all the tools thus far using the anvil. The problem with this, is the use of custom "balls" instead of ingots. Hence my request, since casting could provide a more flexible use of 3rd party materials.
btw, how does casting work? I assume I place a casting block on a forge, add the cast. but then what? I thought pouring in the metal from a crucible, but I can't seem to get that to work. Does the castingform come into the equation somewhere? Haven't figured out what that is for.
Awesome mod in combo with primal. Love both mods. Only downside is the limited manual/wiki. If I figure it all out I wouldn't mind helping out with a wiki or in-game manual if you guys have one?

**Comment by kitsushadow** [comment] 2017-09-23 11:59
U use the casting form to make casts, the cast will change color when it
dries. Place the form in the casting block. The casting block can b
wherever. Heat a bronze crucible of the variation u so choose and grab it
with the tongs when ready. Right click the casting block with the tongs and
ull get ur cast bronze tool.

 I don't have the casts in the wiki but its basically the opposite of the
anvil recipes.

On Sep 23, 2017 7:03 AM, "Ash70" <notifications@github.com> wrote:

I see. I made a lot of assumptions since I am not entirely sure how the
casting mechanism works. I made all the tools thus far using the anvil. The
problem with this, is the use of custom "balls" instead of ingots. Hence my
request, since casting could provide a more flexible use of 3rd party
materials.
btw, how does casting work? I assume I place a casting block on a forge,
add the cast. but then what? I thought pouring in the metal from a
crucible, but I can't seem to get that to work. Does the castingform come
into the equation somewhere? Haven't figured out what that is for.
Awesome mod in combo with primal. Love both mods. Only downside is the
limited manual/wiki. If I figure it all out I wouldn't mind helping out
with a wiki or in-game manual if you guys have one?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/kitsushadow/forgecraft/issues/24#issuecomment-331626852>,
or mute the thread

**Comment by kitsushadow** [comment] 2017-09-23 12:00
You have seen my wiki right? Have you used Google sites b4?

**Comment by kitsushadow** [comment] 2017-10-04 17:30
gonna close this

**Closed by kitsushadow** 2017-10-04 17:30 UTC

**Comment by Ash70** [comment] 2017-10-05 09:38
Sorry, forgot about this. Bit of a crisis IRL atm.
np.
